services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rbag_elections_dev
    command: sleep infinity
    ports:
      - 4000:4000
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match should match what your application expects. In this case, the
      # compose file is in a sub-folder, so we will mount '..'. We'll then reference this
      # as the workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace:cached

      # This lets you avoid setting up Git again in the container
      # - ~/.gitconfig:/root/.gitconfig
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rbag_elections_dev

volumes:
  pg-data:
